### ISSUE TITLE
OperatorAutoConfiguration with metrics

### ISSUE THREAD

**Issue by mteubner** [java-operator-sdk/operator-framework-spring-boot-starter#14]
Hello,

is there a way to configure the Operator with Metrics?

I'm currently using the java-operator-sdk with ConfigurationServiceOverrider to add MicrometerMetrics. Now I want to change to spring boot for adding actuator, and otherthings to the operator, but I struggle to configure the configuration, without override the AutoConfig Implementation.

Kind Regards

**Comment by csviri** [comment]
HI @mteubner , it does not seems to.
I can take a look later, but quite busy, so probably just in 1-2 weeks, care to take a PR and fix that :) ?

**Comment by mteubner** [comment]
Hi @csviri, I currently see no easy way of doing so ;)

The main issue is that the metrics-support is optional so it shall not be needed when using the starter right?

We could change the OperatorAutoConfiguration to implement getMetrics somehow, but I'm currently don't know how to inject optional classes without making them dependent.

So I don't know if there would be an easy way to make this injectable.

**Comment by csviri** [comment]
Good question, pretty sure that this is doable, but might not be trivial indeed. Will try to take a look if can find some time.

**Comment by kroonprins** [comment]
hello, similarly I think it could be useful to allow the configuration of an ExecutorService. It seems a bit the same situation as for metrics that it has a default implementation in ConfigurationService that OperatorAutoConfiguration does not override. For the executor service, it is possible to configure a part of it (the number of reconcilation threads), but it would be nice to have more/total control over the used executor.

**Comment by kroonprins** [comment]
if not too naive as solution, I can propose this commit https://github.com/kroonprins/operator-framework-spring-boot-starter/commit/41ac1f2afaf990665c43f6b9f22c4c0d27b92eca in a PR

**Comment by robzienert** [comment]
This looks closable.
