### ISSUE TITLE
Request to support OAuth Token as kubernetes client credentials in operator-framework-spring-boot-starter

### ISSUE THREAD

**Issue by zhannicholas** [java-operator-sdk/operator-framework-spring-boot-starter#21]
In `operator-framework-spring-boot-starter module`, username/password authentication is supported for newly created kubernetes client. However, in some cases, username/password is unsupported and only OAuth token is supported, the later one is more secure. Maybe we can support both.

More details are in method `io.javaoperatorsdk.operator.springboot.starter.OperatorAutoConfiguration#getClientConfiguration`:
```
xxx
.orElseGet(() -> {
          final var clientCfg = configuration.getClient();
          ConfigBuilder config = new ConfigBuilder();
          config.withTrustCerts(clientCfg.isTrustSelfSignedCertificates());
          clientCfg.getMasterUrl().ifPresent(config::withMasterUrl);
          clientCfg.getUsername().ifPresent(config::withUsername);
          clientCfg.getPassword().ifPresent(config::withPassword);
```
More details can be found at [java-operator-sdk issue 1282](https://github.com/java-operator-sdk/java-operator-sdk/issues/1282).

**Comment by csviri** [comment]
Thx @zhannicholas . Do you plan also to work on this?

**Comment by zhannicholas** [comment]
Yeah😁
