### ISSUE TITLE
Received event after patch using @EnableMockOperator

### ISSUE THREAD

**Issue by jmformenti** [java-operator-sdk/operator-framework-spring-boot-starter#30]
I found a weird behaviour creating a test using `@EnableMockOperator`.

When I return the control using `patchStatus`:
```
return UpdateControl.patchStatus(resource);
```
I receive immediately a new event for that resource, but if I'm not wrong, this is not the behaviour expected. I mean in a real Kubernetes cluster after `patchStatus` I don't receive a new event for that resource.

In the other hand, if I use `updateStatus` with `@EnableMockOperator`it works fine, I mean I don't receive a new event.

**Comment by csviri** [comment]
Hi @jmformenti 
this seems to be an issue in mock server. Pls create an issue in Fabric8 Client:
https://github.com/fabric8io/kubernetes-client

Since the mock server is implemented there.
thank you!

**Comment by jmformenti** [comment]
Oh, my bad, there was a stupid mistake on my side.
Now it's working fine :+1:
