### ISSUE TITLE
Update to newest version

### ISSUE THREAD

**Issue by xintellion** [java-operator-sdk/operator-framework-spring-boot-starter#33]
Just a short questions. it seems that the spring boot starter is a few versions behind the actual sdk. Are there any plans to release a new version? If I'm not wrong than the sdk is already on 4.2.7 while the starter is still on 4.1.1

**Comment by csviri** [comment]
Hi @xintellion , already working on it, should be available end of this week.

**Comment by xintellion** [comment]
That are great news!
