### ISSUE TITLE
Spring Boot 3 Compatibility

### ISSUE THREAD

**Issue by kosmoz** [java-operator-sdk/operator-framework-spring-boot-starter#34]
Auto configuration is currently not working in projects using Spring Boot 3, because the `spring.factories` file is no longer supported ([source](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files)).

There might be more issues, but I did not get past auto configuration.

Are there any plans to add support for Spring Boot 3?

**Comment by csviri** [comment]
Yes, there is a plan. Will create an issue. But might take some time, because of our current bandwidth. So contribution is welcome :)

**Comment by csviri** [comment]
now it is supported! closing the issue
